spring.application.name=digitalfix-ms-catalog
server.port=8081

# Conexion Oracle RDS mediante variables de entorno
spring.datasource.url=jdbc:oracle:thin:@//digitalfix.c1ligwfwziy9.us-east-1.rds.amazonaws.com/ORCL
spring.datasource.username=admin
spring.datasource.password=Duocvalparaiso.2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA crea y actualiza las tablas necesarias sin borrar los datos existentes
spring.jpa.hibernate.ddl-auto=update

# Evita mantener sesiones de persistencia abiertas durante toda la respuesta HTTP
spring.jpa.open-in-view=false